### ISSUE TITLE
Train model for univariate time series

### ISSUE THREAD

**Issue by isCopyman** [decisionintelligence/TFB#11]
The paper states, "In this scenario, each individual univariate time series is adopted to train a separate model, and deep learning methods require a large amount of training data to be effective. Therefore, the performance of the deep learning methods falls short." Your univariate dataset comprises over 8,000 individual time series. Does this mean that each deep learning method is trained and predicts on a single series, implying that one method trains 8,000 models?

**Comment by qiu69** [comment]
Thank you for your attention and questions！ For each univariate data in over 8000 univariate time series, deep learning method trains separately on each series and then predicts that series.

**Comment by isCopyman** [comment]
@qiu69 That's really a computationally demanding task. Evaluating a deep learning method requires constructing over 8000 different models.

**Comment by qiu69** [comment]
You're right,  thank you for your recognition. We've put a lot of effort and computing resources into this work. I hope this publication、code repository can be helpful to researchers.

**Comment by isCopyman** [comment]
A SOLID job indeed. Method evaluation based on categorisation of characteristics of time series can provide good insights. The a priori assumptions introduced in the design process of these models inherently lead them to have such properties, so it is difficult for different models to perform well on all properties, and this benchmark provides a basis for selecting models and designing them.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiangfei ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 晚上8:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [decisionintelligence/TFB] Train model for univariate time series (Issue #11)














 
You're right,  thank you for your recognition. We've put a lot of effort and computing resources into this work. I hope this publication、code repository can be helpful to researchers.

**Comment by qiu69** [comment]
@isCopyman Thank you for your recognition. We hope the publication and code repository can be helpful to you, and we also welcome you to become the developer of our code repository.
