### ISSUE TITLE
About result 

### ISSUE THREAD

**Issue by Sylphid172** [decisionintelligence/TFB#13]
We know that there are over 8000 univariate datasets, and the results of the paper are presented with different attributes (such as year). What I want to ask is how different datasets are counted into this result when calculating the result. I didn't understand after reading the source code

**Comment by qiu69** [comment]
Thank you for your attention and questions！
For each category of dataset (year), we use a different config file to run it (fixed_forecast_config_year. json), and then when we calculate the results, we group them according to their characteristics (seasonal, trend. You can find them in FORECAST_META.csv）， and then we report the mean of all time series results within each group.

**Comment by qiu69** [comment]
Hi, If you have any further questions, please feel free to report them to us. If the problem has been resolved, please close the issue.
