### ISSUE TITLE
Incorporate the Time Series Foundation Model

### ISSUE THREAD

**Issue by Caelyn-gao** [decisionintelligence/TFB#17]
Hi, thanks for the great work.

I noticed that you have offered a way to incorporate our own time series forecasting models, which is great. Recently, there has been a surge in the availability of **time series pretrained foundation models** such as Chronos, Moirai, and Lag-Llama et al.  So I am wondering **if there is a way that I can incorporate these pretrained models, then I can compare large and small models together.**

Thanks in advance!

**Comment by qiu69** [comment]
Hello, Thank you for your attention and questions.  We are currently making attempts in this area, please wait and feel free to give us your feedback！

**Comment by Caelyn-gao** [comment]
That will be great. May I ask when I can try on the way of incorporating time series pretrained foundation models?
Look forward to it!

**Comment by qiu69** [comment]
Although our time is limited, we are still working hard to do it, and his priority is high.
