### ISSUE TITLE
How to evaluate models on my own datasets (hyper-params)

### ISSUE THREAD

**Issue by Caelyn-gao** [decisionintelligence/TFB#18]
Hi, thanks for the great work. It is very useful to help us understand the area of time series forecasting.

If I want to use your pipeline to evaluate models on my own datasets, may I ask how to do it? The important thing is the hyper-params. I noticed that per model, you have given the hyper-params in the scripts you offered. I guess these hyper-params are selected according to hyper-parameter searches or settings in the original papers. If I want to use my own datasets, in the TFB pipeline, is there any module that I can get the best hyper-parameters when training on my own dataset?

Thanks a lot in advance! Have a good day!

**Comment by Caelyn-gao** [comment]
Thanks for the response. It is great!

**Comment by qiu69** [comment]
We provide tutorial about how to evaluate your own time series, please see https://github.com/decisionintelligence/TFB/blob/master/docs/tutorials/steps_to_evaluate_your_own_time_series.md
