### ISSUE TITLE
Add an Example of Customizable Model

### ISSUE THREAD

**Issue by profEraylson** [decisionintelligence/TFB#22]
Hello,

First of all, I would like to congratulate the team for the great idea and excellent work on this project.

I am having difficulty adding a custom class to the pipeline. I would like to suggest adding an example in the documentation that demonstrates how to include a custom model in the pipeline.

The steps described in the current documentation were not sufficient for me to successfully achieve this integration.

Thank you!

**Comment by qiu69** [comment]
Thank you for your attention and question. We are currently planning to provide detailed instructions on how to use users' own datasets and embed their own algorithms.

**Comment by qiu69** [comment]
We provide tutorial about how to develop your own method. Please see https://github.com/decisionintelligence/TFB/blob/master/docs/tutorials/steps_to_develop_your_own_method.md.

**Comment by qiu69** [comment]
Hi, If you have any further questions, please feel free to report them to us. If the problem has been resolved, please close the issue.
