### ISSUE TITLE
Verify data correlation

### ISSUE THREAD

**Issue by starry-ZRY** [decisionintelligence/TFB#28]
Hello, I'd like to check if my data has strong correlations. How can I run this using your code block?

**Comment by qiu69** [comment]
Hello, Thank you for your attention and questions. 
We provided a process description in the paper, sorry we did not provide the code.
<img width="638" alt="image" src="https://github.com/user-attachments/assets/422831c6-d02d-4bde-a782-2a9418ec46d7">

**Comment by starry-ZRY** [comment]
Alright, thank you for your response. I was wondering if it would be convenient for you to provide it?
![微信截图_20240925150559](https://github.com/user-attachments/assets/899d4659-1117-4eb3-976c-f8fc2d06aa1e)

**Comment by qiu69** [comment]
If you're not in a hurry, I can provide it to you in 10 days. Because there have been other urgent matters recently.

**Comment by starry-ZRY** [comment]
Thank you, I can wait. You can send it to my email. My email is: 23120158@bjtu.edu.cn

**Comment by qiu69** [comment]
Hi, If you have any further questions, please feel free to report them to us. If the problem has been resolved, please close the issue.

**Comment by trunghieuvu02** [comment]
Hi @qiu69,

I am really interested in your work and would like to apply it to our private dataset. Could you provide the code to analyze dataset characteristics, including trend, seasonality, stationarity, shifting, transition, and correlation? I would really appreciate it if you could do it.

**Comment by qiu69** [comment]
@trunghieuvu02 can you show me your email?

**Comment by trunghieuvu02** [comment]
@qiu69 

Please send it to my personal email: trunghieu02111998@gmail.com
Thank you very much for your support.

**Comment by qiu69** [comment]
Hi, If you have any further questions, please feel free to report them to us. If the problem has been resolved, please close the issue.

**Comment by lc7335** [comment]
Hi @qiu69,

I am very interested in your work and hope to apply it to our private data set. Could you provide code to analyze the characteristics of the data set, including trends, seasonality, stationarity, shifts, transformations, and correlations? I would be extremely grateful if you could do so. 
If possible, please send it to my personal email: lc954395165@gmail.com

**Comment by yushu-fish** [comment]
@qiu69 Could you kindly share a comprehensive code for analyzing dataset characteristics? It would be great if the analysis could address aspects like trend, seasonality, stationarity, shifting, transition, and correlation. I truly appreciate your help.my my personal email: 834012884@qq.com

**Comment by BraudoCC** [comment]
@qiu69 Hello, I am also interested in obtaining the code for analyzing trend, seasonality, stationarity, shifting, transition, and correlation in time series. Could you please provide me with a copy? Thank you very much！my personal email: houchaochuan@foxmail.com

**Comment by zhangchenhaobest** [comment]
@qiu69 Hello, Thank you for your wonderful job!  Could you provide some calculation code for analyzing trend, seasonality, stationarity, shifting, transition, and correlation in time series. Thank you very much！
If possible, please send it to my personal email: 478951530@qq.com

**Comment by qiu69** [comment]
TFB has open-sourced the [code](https://github.com/decisionintelligence/TFB/blob/master/characteristics_extractor/Characteristics_Extractor.py) for computing time series characteristics, such as trend, seasonality, stationarity, shifting, transition, correlation, and more. Both [Chinese](https://github.com/decisionintelligence/TFB/blob/master/characteristics_extractor/Readme_chn.md) and [English](https://github.com/decisionintelligence/TFB/blob/master/characteristics_extractor/Readme_en.md) documentation are provided.

**Comment by zhangchenhaobest** [comment]
邮件已收到
