### ISSUE TITLE
How to obtain the FORECAST_META.csv file?

### ISSUE THREAD

**Issue by LETUSFLYLPF** [decisionintelligence/TFB#29]
Hello，Thank you for your open source work！When I followed the instructions to process my own dataset, and I'm using the git bash terminal in pycharm，I get the following error：
<img width="919" alt="{047BCC7D-4BBC-41B4-A2F0-6C68CE916A1B}" src="https://github.com/user-attachments/assets/d4da3782-88d5-4377-9213-14caf3983891">
So I cancel operations like escaping double quotes,and get the following error:
<img width="841" alt="{C8AE0C86-D20E-4329-A8A1-97AE69DBDE7E}" src="https://github.com/user-attachments/assets/48e7d8a3-c215-4292-8aab-a9d7e792231a">
Then I didn't know how to proceed with it

**Comment by qiu69** [comment]
Thank you for your question and attention!
<img width="870" alt="image" src="https://github.com/user-attachments/assets/22570d49-0306-4040-bc8e-c3af0c4111c4">

**Comment by qiu69** [comment]
Hi, If you have any further questions, please feel free to report them to us. If the problem has been resolved, please close the issue.
