### ISSUE TITLE
About leaderborad

### ISSUE THREAD

**Issue by isCopyman** [decisionintelligence/TFB#39]
![image](https://github.com/user-attachments/assets/ec9673da-2e34-44b4-820d-1fdad342f604)
What is the DUET, I can't open it.

**Comment by lc7335** [comment]
What is the DUET, I can't open it.

**Comment by qiu69** [comment]
Thank you for your attention! DUET is our accepted paper on time series forecasting for KDD 2025. We are currently organizing the code and refining the paper, and it will be uploaded to arXiv soon. Stay tuned!

**Comment by qiu69** [comment]
To @lc7335 and @isCopyman,
You can find DUET in this paper: https://arxiv.org/pdf/2412.10859.
The corresponding code is available here: https://github.com/decisionintelligence/DUET.
