### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by WenWeiTHU** [decisionintelligence/TFB#4]
Time seires Forecasting Benchmark -> Time Series Forecasting Benchmark

**Comment by qiu69** [comment]
Thank you for you suggestion！
We are further optimizing our code and welcome any suggestions for modifications.
<img width="642" alt="image" src="https://github.com/decisionintelligence/TFB/assets/82441982/2abf0c69-8362-4629-8fb4-c7c72e70cdf3">

**Comment by WenWeiTHU** [comment]
Okay, I think it is a great work! Please also note the "Series"

**Comment by qiu69** [comment]
Thank you for your reminder!
