### ISSUE TITLE
Source of univariate datasets

### ISSUE THREAD

**Issue by gorold** [decisionintelligence/TFB#6]
Hi, thanks for the great work. I'm trying to understand the breakdown and source for the univariate time series. From the paper, I only managed to extract the following: "The univariate datasets are carefully curated from 16 open-source datasets". Are there more details on the details of the unvariate time series?

**Comment by qiu69** [comment]
Thank you, here are the names and sources of the original univariate dataset：
1、M1: https://www.jstor.org/stable/2345077?origin=crossref
2、M3: https://www.sciencedirect.com/science/article/abs/pii/S0169207000000571?via%3Dihub
3、M4: https://www.sciencedirect.com/science/article/pii/S0169207019301128?via%3Dihub
4、Libra: https://zenodo.org/records/4399959
5、Dominick: https://www.chicagobooth.edu/research/kilts/research-data/dominicks
6、US Births: https://cran.r-project.org/web/packages/mosaicData/
7、Bitcoin: Monash Time Series Forecasting Archive
8、Weather: https://cran.r-project.org/web/packages/bomrang/
9、KDD Cup 2018: https://www.kdd.org/kdd2018/kdd-cup
10、Web Traffic: https://www.kaggle.com/c/web-traffic-time-series-forecasting
11、Pedestrian Counts: https://data.melbourne.vic.gov.au/Transport/Pedestrian-Counting-System-Monthly-counts-per-hour/b2ak-trbp
12、Aus. Electricity Demand: Monash Time Series Forecasting Archive
13、Tourism: https://www.sciencedirect.com/science/article/abs/pii/S016920701000107X?via%3Dihub
14、CIF 2016: https://ieeexplore.ieee.org/document/8015455
15、Vehicle Trips: https://github.com/fivethirtyeight/uber-tlc-foil-response
16、Saugeen River Flow: http://www.jenvstat.org/v04/i11

welcome to provide feedback on our paper and code!
