### ISSUE TITLE
Cannot repeat the experiment results of LTSF.

### ISSUE THREAD

**Issue by BoffinZhang** [decisionintelligence/TFB#9]
With default setting, I tried to repeat the experiment of LTSF (PatchTST on ETTh1, both look-back window and predict window have length of 96). But the results seem completely different from the paper. 
<img width="899" alt="patchTST-results" src="https://github.com/decisionintelligence/TFB/assets/32448308/ab7e68bf-1d2f-457a-ab86-18dee3277e1d">

[test_report.csv](https://github.com/decisionintelligence/TFB/files/15414885/test_report.csv)

Are there any further steps to process the report?

**Comment by qiu69** [comment]
Thank you for your attention and question, the test_report.csv stores the results calculated after de_normalization. You can unzip the generated zip file, and the metric results ending in _norm are the normalized results, which are the multivariate forecasting results in the paper. 
The results corresponding to the metrics shown in the red box in the following figure are the normalized results.
<img width="1380" alt="image" src="https://github.com/decisionintelligence/TFB/assets/82441982/5fad17d5-ed80-42d1-8c5a-c20f550ba2f2">

**Comment by BoffinZhang** [comment]
Thank you for your timely response. The issue is closed.
